#!/usr/bin/env perl
#
# The build-system is Copyright (C) 2017 Alexander Kuleshov <kuleshovmail@gmail.com>,
#
# Github: https://github.com/0xAX/kernel-dev/tree/master/kernel-testing

use strict;
use warnings "all";
use diagnostics;

use YAML;
use Getopt::Long;

require "./scripts/disk.pm";

# specification file that will be processed
my $spec = '';
# specification content
my $spec_data = '';

# help and version flags
my $help = '';
my $version = '';

GetOptions(
    "spec=s" => \$spec,
    "help" => \$help,
    "version" => \$version)
    or die("Wrong set of command line arguments were passed\n");

if ($spec eq '') {
    print STDERR "Error: specification must be provided\n";
    exit 1;
}

open(my $spec_fd, "<", $spec)
    or die("Error: can't read given specification - $!");

$spec_data = do {local $/; <$spec_fd>};

close($spec_fd)
    or warn "Error: can't close specification file - $!";

exit 0;
